DOMAIN = "gtt_bus"

API_URL = "http://gpa.madbob.org/query.php"
API_MAX_ATTEMPTS = 2
API_RETRY_DELAY_SECONDS = 10
API_TIMEOUT_SECONDS = 10
ATTRIBUTION = "Data provided by the unofficial GTT Pirate API"

DEFAULT_NAME = "GTT Bus"
CONF_STOPS = "stops"
CONF_SCAN_INTERVAL = "scan_interval"
DEFAULT_SCAN_INTERVAL = 60
MIN_SCAN_INTERVAL = 30
DEPARTURE_SENSOR_COUNT = 6
SENSOR_STATE_MAX_LENGTH = 255
